In [1]:
import numpy as np
import importlib
import matplotlib.pyplot as plt
import seaborn as sns
import src.flow_ot as fo
importlib.reload(fo)

<module 'src.flow_ot' from '/Users/kaihung/optimalEnsemble/OTFactorDiscovery/kai/src/flow_ot.py'>

In [2]:
# define function for visualizing the resulting densities
def kde_barycenter_points(y, gauss_a, gauss_b): 
    fig, ax = plt.subplots(figsize=(12, 6))
    sns.kdeplot(data=gauss_a,
                color='crimson', label='A', fill=True, ax=ax)
    sns.kdeplot(data=gauss_b,
                color='limegreen', label='B', fill=True, ax=ax)
    sns.kdeplot(data=y, 
                color='purple', label='y', fill=True, ax=ax)
    ax.legend()
    plt.title(f"Barycenter Estimation")
    plt.show()
# simulate gaussian dataset
np.random.seed(125)
SIZE = 20
CLASSES = 2
x1 = np.random.normal(-1, 1, SIZE)
x2 = np.random.normal(1, 1, SIZE)
# process the simulated data into the desired form
x = np.concatenate((x1, x2)).reshape((2 * SIZE, 1))
z = np.zeros((x.shape[0], 1), dtype=np.int64)
z[SIZE:] = 1
z_map = np.array([0, 1])
# determine the masking ratio
# MASK = np.full(x.shape[0], 1)
# TODO: uncomment the following if testing for mixtures 
PROP = 0.2
NUM_UNKNOWN = int(PROP * 2 * SIZE)
MASK = np.random.choice(2 * SIZE, size=NUM_UNKNOWN)
z[MASK] = -1
# set-up for the SSL procedure 
ssl_ot = fo.SemiSupervisedOT()
ssl_ot.initialize(x, z, CLASSES, z_map)

In [4]:
MASK

array([15, 21,  9, 35,  1, 19, 26, 27])

In [10]:
y = ssl_ot.train(x, verbose=2, max_iter=2, growing_lambda=False, fixed_lam=250)
filtered_y, assignments = ssl_ot.select_best(y)

[[[ 2.77555756e-14]
  [ 0.00000000e+00]]

 [[ 7.22712722e-16]
  [ 7.22712722e-16]]

 [[-1.11022302e-13]
  [-0.00000000e+00]]

 [[-1.38777878e-14]
  [-0.00000000e+00]]

 [[ 0.00000000e+00]
  [ 0.00000000e+00]]

 [[ 2.77555756e-14]
  [ 0.00000000e+00]]

 [[ 1.11022302e-13]
  [ 0.00000000e+00]]

 [[ 1.38777878e-14]
  [ 0.00000000e+00]]

 [[ 0.00000000e+00]
  [ 0.00000000e+00]]

 [[ 0.00000000e+00]
  [ 0.00000000e+00]]

 [[ 5.55111512e-14]
  [ 0.00000000e+00]]

 [[ 0.00000000e+00]
  [ 0.00000000e+00]]

 [[-1.38777878e-14]
  [-0.00000000e+00]]

 [[ 0.00000000e+00]
  [ 0.00000000e+00]]

 [[ 6.93889390e-15]
  [ 0.00000000e+00]]

 [[ 4.16686439e-16]
  [ 4.16686439e-16]]

 [[-2.77555756e-14]
  [-0.00000000e+00]]

 [[ 0.00000000e+00]
  [ 0.00000000e+00]]

 [[-2.77555756e-14]
  [-0.00000000e+00]]

 [[-2.49735180e-16]
  [-2.49735180e-16]]

 [[-0.00000000e+00]
  [-5.55111512e-14]]

 [[ 0.00000000e+00]
  [ 0.00000000e+00]]

 [[ 0.00000000e+00]
  [ 0.00000000e+00]]

 [[ 0.00000000e+00]
  [ 5.55111512

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [ ]:
kde_barycenter_points(filtered_y, x1, x2)